import { Footer } from '@/components/common/Footer';
import Header from '@/components/common/Header';
import { FixedBottomCTA } from '@/components/fixed-bottom-cta';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale } from 'next-intl/server';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <body
        className={`relative flex flex-col ${geistSans.variable} ${geistMono.variable} font-sans min-h-screen`}
      >
        <NextIntlClientProvider>
          <Header />
          {children}
          <Footer />
          <FixedBottomCTA />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
